### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by Himself132** [dnkolegov/bigipsecurity#2]
Hello, stuck at the step for "cargo build" everything else up to this point has been done without exclusion.  Running into the following error:

 cargo build --verbose
       Fresh autocfg v0.1.5
       Fresh unicode-xid v0.1.0
       Fresh version_check v0.1.5
       Fresh cc v1.0.40
       Fresh glob v0.2.11
       Fresh rustc-serialize v0.3.24
       Fresh lazy_static v1.3.0
       Fresh quick-error v1.2.2
       Fresh unicode-width v0.1.5
       Fresh cfg-if v0.1.9
       Fresh regex-syntax v0.6.11
       Fresh vec_map v0.8.1
       Fresh termcolor v1.0.5
       Fresh ansi_term v0.11.0
       Fresh strsim v0.8.0
       Fresh peeking_take_while v0.1.2
       Fresh strsim v0.9.2
       Fresh proc-macro2 v0.3.5
       Fresh thread_local v0.3.6
       Fresh humantime v1.2.0
       Fresh textwrap v0.11.0
       Fresh libc v0.2.61
       Fresh proc-macro2 v0.4.30
       Fresh memchr v2.2.1
       Fresh log v0.4.8
       Fresh bitflags v1.1.0
       Fresh quote v0.5.2
       Fresh num-traits v0.2.8
       Fresh rand v0.4.6
       Fresh quote v0.6.13
       Fresh aho-corasick v0.7.6
       Fresh atty v0.2.13
       Fresh libloading v0.5.2
       Fresh nom v4.2.3
       Fresh which v1.0.5
       Fresh num-integer v0.1.41
       Fresh syn v0.15.44
       Fresh num-complex v0.1.43
       Fresh regex v1.2.1
       Fresh clang-sys v0.26.4
       Fresh cexpr v0.3.5
       Fresh clap v2.33.0
       Fresh num-bigint v0.1.44
       Fresh serde_derive v1.0.98
       Fresh num-iter v0.1.39
       Fresh env_logger v0.5.13
       Fresh num-rational v0.1.42
       Fresh serde v1.0.98
       Fresh bindgen v0.43.1 (https://github.com/rust-lang-nursery/rust-bindgen.git?tag=v0.43.1#5de943ca)
       Fresh num v0.1.42
       Fresh docopt v1.1.0
       Fresh enum_primitive v0.0.2
   Compiling tclscan v0.0.1 (tclscan-master)
     Running `rustc --crate-name tclscan src/main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=aff5985de877bcda -C extra-filename=-aff5985de877bcda --out-dir tclscan-master/target/debug/deps -C incremental=tclscan-master/target/debug/incremental -L dependency=tclscan-master/target/debug/deps --extern bindgen=tclscan-master/target/debug/deps/libbindgen-6959e6659a78f3eb.rlib --extern docopt=tclscan-master/target/debug/deps/libdocopt-5edf88a106dc94f1.rlib --extern enum_primitive=tclscan-master/target/debug/deps/libenum_primitive-a74fe5b0b39500c8.rlib --extern num=tclscan-master/target/debug/deps/libnum-13517b8b1a732bae.rlib --extern rustc_serialize=tclscan-master/target/debug/deps/librustc_serialize-24afca0fce6e4809.rlib --extern tclscan=tclscan-master/target/debug/deps/libtclscan-1ccbb5dc0ec457f9.rlib -L native=tclscan-master/target/debug/build/libloading-f7adb469de5f380b/out`
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.19c27hfesixid86i.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.1a8agivucgohis9u.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.1d0dpvkq9tlrmnvh.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.1mkktyyr1yhkmp0j.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.1picso8jtg06gyvw.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.1qeeql2izwmljil1.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.1vl6o03dxt1soymp.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.1zxdsunudnzbrepm.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.205x4tbk0yn7afz6.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.2ck74exp8slz0mgc.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.2co08nonkfz3ika6.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.2fztttm7yupzf5po.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.2j51dt6cv4yt0pnl.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.2ufyzuzxqo5c2x63.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.2w3uo0etldftefos.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.2xsd0aoxe4a2ena9.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.3e7ay1m7ej4vbat6.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.3juwpfw5si7uk3m7.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.3n5eocxeo5zgvbjd.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.3qy2zotfrv677ds0.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.3vjbvlf318ze4n4c.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.3wdo0k7s33efxnbz.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.45u81zvxixdpg29j.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.4bp0r7i7fea8rd89.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.4m0yqqcvmvk0repx.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.4mk1jilaoyuxh8bm.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.4onmz0bxskjkbda4.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.4povtjcqe6m2t7po.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.4qnm73b5led6hmbw.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.50xqstwgpa3242be.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.520os3j0ys5ms26h.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.58zzzn35u2rk32rq.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.5bka7hnlk946ixe2.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.7c7gh8q6f3hjrqu.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.87epesu8dwbctby.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.9nm6w8tx0fh6i09.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.i2znk93x6rwbipo.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.lpfutw24kdonet7.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.uq1dsi7375h1li3.rcgu.o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.x00zqypime6rket.rcgu.o" "-o" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda" "tclscan-master/target/debug/deps/tclscan-aff5985de877bcda.3go5xueqdqxpnx5i.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "tclscan-master/target/debug/deps" "-L" "tclscan-master/target/debug/build/libloading-f7adb469de5f380b/out" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "tclscan-master/target/debug/deps/libtclscan-1ccbb5dc0ec457f9.rlib" "tclscan-master/target/debug/deps/libenum_primitive-a74fe5b0b39500c8.rlib" "tclscan-master/target/debug/deps/libnum-13517b8b1a732bae.rlib" "tclscan-master/target/debug/deps/libnum_rational-a1e99edfc939107e.rlib" "tclscan-master/target/debug/deps/libnum_bigint-3940dffd76f6c8d0.rlib" "tclscan-master/target/debug/deps/librand-b7c836b19d8fc6a5.rlib" "tclscan-master/target/debug/deps/liblibc-019013c42cedcbef.rlib" "tclscan-master/target/debug/deps/libnum_complex-8247f0caa5cd75da.rlib" "tclscan-master/target/debug/deps/libnum_iter-150ea57f77c45e0e.rlib" "tclscan-master/target/debug/deps/libnum_integer-c15b361466f7356a.rlib" "tclscan-master/target/debug/deps/libnum_traits-4d7bec640469e574.rlib" "tclscan-master/target/debug/deps/libdocopt-5edf88a106dc94f1.rlib" "tclscan-master/target/debug/deps/libstrsim-f0003285ba2f7ffc.rlib" "tclscan-master/target/debug/deps/libserde-027f85c70627b177.rlib" "tclscan-master/target/debug/deps/libregex-baf24738b2060b56.rlib" "tclscan-master/target/debug/deps/libregex_syntax-8b64db34f439f8e3.rlib" "tclscan-master/target/debug/deps/libthread_local-2bad11982f0bfaea.rlib" "tclscan-master/target/debug/deps/libaho_corasick-32d316c5d92cc8b2.rlib" "tclscan-master/target/debug/deps/libmemchr-29d6bc0a21a32abb.rlib" "tclscan-master/target/debug/deps/liblazy_static-f7ca2f8b93240e2f.rlib" "tclscan-master/target/debug/deps/librustc_serialize-24afca0fce6e4809.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-ea78b296dfcb1bd1.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-4c07bc9d017a864f.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-cf3daf3496a1bc13.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-4fe2fc8d86757dfc.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-d7fc730ed195761f.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-167fd636fc247f1a.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-ea09fdf38cc7f13b.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-f4ddf37e4fbb45a9.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-e98a89325b0a5624.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-5ca7e51beffe9e3a.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-051e97aeffb6b0af.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-b869730f5ae991f6.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-6d9f294ab10b95af.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-32407cf90cbd3164.rlib" "-Wl,-Bdynamic" "-lutil" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/bin/ld: tclscan-master/target/debug/deps/libtclscan-1ccbb5dc0ec457f9.rlib(tclscan-1ccbb5dc0ec457f9.55yrzhrx4tlonw9e.rcgu.o): in function `tclscan::rstcl::tcl_interp':
          tclscan-master/src/rstcl.rs:12: undefined reference to `Tcl_CreateInterp'
          /usr/bin/ld: tclscan-master/target/debug/deps/libtclscan-1ccbb5dc0ec457f9.rlib(tclscan-1ccbb5dc0ec457f9.55yrzhrx4tlonw9e.rcgu.o): in function `tclscan::rstcl::parse':
          tclscan-master/src/rstcl.rs:270: undefined reference to `Tcl_ParseCommand'
          /usr/bin/ld: tclscan-master/src/rstcl.rs:272: undefined reference to `Tcl_ParseExpr'
          /usr/bin/ld: tclscan-master/src/rstcl.rs:304: undefined reference to `Tcl_FreeParse'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `tclscan`.

Caused by:
  process didn't exit successfully: `rustc --crate-name tclscan src/main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=aff5985de877bcda -C extra-filename=-aff5985de877bcda --out-dir tclscan-master/target/debug/deps -C incremental=tclscan-master/target/debug/incremental -L dependency=tclscan-master/target/debug/deps --extern bindgen=tclscan-master/target/debug/deps/libbindgen-6959e6659a78f3eb.rlib --extern docopt=tclscan-master/target/debug/deps/libdocopt-5edf88a106dc94f1.rlib --extern enum_primitive=tclscan-master/target/debug/deps/libenum_primitive-a74fe5b0b39500c8.rlib --extern num=tclscan-master/target/debug/deps/libnum-13517b8b1a732bae.rlib --extern rustc_serialize=tclscan-master/target/debug/deps/librustc_serialize-24afca0fce6e4809.rlib --extern tclscan=tclscan-master/target/debug/deps/libtclscan-1ccbb5dc0ec457f9.rlib -L native=tclscan-master/target/debug/build/libloading-f7adb469de5f380b/out` (exit code: 1)

**Comment by hazcod** [comment]
Wrong repo?
